#this is an example file

#starting delay to set up the screen
wait=5000

rclick=742,186
wait=3500

loop=1
click=391,527
wait=500
click=128,764
wait=2000
click=915,342
wait=500
endloop

loop=3
dbclick=663,211
wait=250

#nested loop
loop=2
click=478,689
wait=1000
click=834,156
wait=1000
endloop

endloop